....

== PARTITIONED VIEW

create view IF NOT EXISTS harshal_galaxy.viewp2 partitioned on (detector_id) as SELECT
detectors.detector_name,
detectors.country,
detectors.latitude,
detectors.longitude,
astrophysicists.astrophysicist_name, astrophysicists.year_of_birth,
astrophysicists.nationality,
galaxies.galaxy_name, galaxies.galaxy_type, galaxies.distance_ly,
galaxies.absolute_magnitude, galaxies.apparent_magnitude,
galaxies.galaxy_group,
measurements.measurement_id,
measurements.measurement_time,
measurements.amplitude_1,
measurements.amplitude_2,
measurements.amplitude_3,
detectors.detector_id
FROM harshal_galaxy.measurments as measurements
join harshal_galaxy.detectors ON measurements.detector_id = detectors.detector_id
join harshal_galaxy.astrophysicists ON measurements.astrophysicist_id = astrophysicists.astrophysicist_id
join harshal_galaxy.galaxies ON measurements.galaxy_id = galaxies.galaxy_id; 


== Merged Table

CREATE TABLE harshal_galaxy.merged
(
detector_name STRING,
country STRING,
latitude DECIMAL(15,6),
longitude DECIMAL(15,6),
astrophysicist_name STRING,
year_of_birth INT,
nationality STRING,
galaxy_name STRING,
galaxy_type STRING,
distance_ly DECIMAL(10,5),
absolute_magnitude DECIMAL(10,5),
apparent_magnitude DECIMAL(10,5),
galaxy_group STRING,
measurement_id STRING,
measurement_time INT,
amplitude_1 DECIMAL(15,12),
amplitude_2 DECIMAL(15,12),
amplitude_3 DECIMAL(15,12)
)
PARTITIONED BY (detector_id INT)
STORED AS PARQUET;


INSERT OVERWRITE TABLE harshal_galaxy.merged
PARTITION(detector_id)
SELECT
detectors.detector_name,
detectors.country,
cast(detectors.latitude as DECIMAL(38,5)),
cast(detectors.longitude as DECIMAL(38,5)),
astrophysicists.astrophysicist_name,
cast(astrophysicists.year_of_birth as INT),
astrophysicists.nationality,
galaxies.galaxy_name,
galaxies.galaxy_type,
cast(galaxies.distance_ly as DECIMAL(10,5)),
cast(galaxies.absolute_magnitude as DECIMAL(10,5)),
cast(galaxies.apparent_magnitude as DECIMAL(10,5)),
galaxies.galaxy_group,
measurements.measurement_id,
cast(measurements.measurement_time as INT),
cast(measurements.amplitude_1 as DECIMAL(15,12)),
cast(measurements.amplitude_2 as DECIMAL(15,12)),
cast(measurements.amplitude_3 as DECIMAL(15,12)),
cast(detectors.detector_id as INT)
FROM harshal_galaxy.measurments as measurements
join harshal_galaxy.detectors ON measurements.detector_id = detectors.detector_id
join harshal_galaxy.astrophysicists ON measurements.astrophysicist_id = astrophysicists.astrophysicist_id
join harshal_galaxy.galaxies ON measurements.galaxy_id = galaxies.galaxy_id
WHERE detectors.detector_id is not null;










....
